PLUGIN.englishTranslation = {
	pistol = "Pistol",
	ar2 = "Rifle",
	smg1 = "Sub Machine Gun",
	buckshot = "Shotgun",
	sniperround = "Sniper Rifle",
	["357"] = "Magnum",

    -- These are for item description translation.
    att_rdot = "Red Dot Sight",
    attRDotDesc = "A Small Sight that displays a red dot in the center",
    att_holo = "Holographic Sight",
    attHoloDesc = "A Small sight that displays an aim-assisting image in the center",
    att_scope4 = "4x Scope",
    attScope4Desc = "A Scope that allows you to aim at mid-long distance targets",
    att_scope8 = "8x Scope",
    attScope8Desc = "A Scope that allows you to aim at long distance targets",
    att_muzsup = "Suppressor",
    attSupDesc = "A Suppressor that reduces the sound from the gun",
    att_exmag = "Extended Mag",
    attEMagDesc = "A Magazine that has more rounds capacity",
    att_foregrip = "Foregrip",
    attForeDesc = "A Grip that makes you to aim hip-fire more accurate.",
    att_laser = "Laser Sight",
    attLaserDesc = "A Laser that displays where you're aiming at",
    att_bipod = "Bipod",
    attBipodDesc = "A Bipod that assists your aim.",
    primary = "Primary Weapon",
    secondary = "Secondary Weapon",

    gunInfoDesc = "A Weapon that uses %s Ammunition",
    gunInfoStat = "Damage: %s\nWeapon Type: %s\nMagazine size: %s",
    gunInfoAttachments = "Current attachment: %s",
    
    attDetached = "Attachment has been detached.",
    detTarget = "You need to choose attachment to detach.",
    cantAttached = "This attachment does not fit for this Weapon.",
    alreadyAttached = "There is no slot for this attachment on this weapon.",
    notCW = "This weapon cannot be modded.",
    notAttachment = "This is not valid attachment.",
    noWeapon = "Can't find the target.",

    cwReloading = "Reloading %s%%",
    cwMagKappa = "%s / %s",
    cwGrenades = "%sx Grenade",
    cwEmptyM203 = "Reload M203",
    cwFilledM203 = "M203 Reloaded",
    cw40mm = "%sx Grenade",
    cwGrenType = "Type: %s",
    cwUse = "[USE]", 
    cwStablize = "%s - Stabilize",

    cwAmmo_ar2 = "Rifle Ammo",
    cwAmmo_smg1 = "SMG Ammo",
    cwAmmo_pistol = "Pistol Ammo",
    cwAmmo_357 = "Magnum Ammo",
	cwAmmo_sniperround = "Sniper Rifle Ammo",
	cwAmmo_buckshot = "Buckshot Ammo",
}

PLUGIN.koreanTranslation = {
	["Pistol Ammo"] = "권총 탄약",
	["Magnum Ammo"] = "매그넘 탄약",
	["Sub Machine Gun Ammo"] = "기관권총 탄약",
	["Rifle Ammo"] = "소총 탄약",
	["Shotgun Shells"] = "산탄총 탄약",
	["Sniper Rounds"] = "저격소총 탄약",

	pistol = "권총",
	ar2 = "소총",
	smg1 = "기관권총",
	buckshot = "산탄총",
	sniperround = "저격소총",
	["357"] = "매그넘",

	gunInfoDesc = "%s 를 사용하는 총기",
	gunInfoStat = "데미지: %s\n무기 종류: %s\n탄창 크기: %s발",
	gunInfoAttachments = "현재 부착물:%s",

    -- These are for item name translation.
    ["Red Dot Sight"] = "레드 닷 조준기",
    ["Holographic Sight"] = "홀로그래픽 조준기",
    ["4x Scope"] = "4배율 조준경",
    ["8x Scope"] = "8배율 조준경",
    ["Suppressor"] = "소음기",
    ["Extended Mag"] = "확장 탄알집",
    ["Foregrip"] = "수직 손잡이",
    ["Laser Sight"] = "레이저 조준기",
    ["Bipod"] = "양각대",

    -- These are for item description translation.
    att_rdot = "레드 닷 조준기",
    attRDotDesc = "조준을 도와주는 레드닷 조준기.",
    att_holo = "홀로그래픽 조준기",
    attHoloDesc = "조준을 도와주는 홀로그래픽 조준기",
    att_scope4 = "4배율 조준경",
    attScope4Desc = "멀리 있는 목표를 조준할 수 있게 해주는 4배율 조준경",
    att_scope8 = "8배율 조준경",
    attScope8Desc = "멀리 있는 목표를 조준할 수 있게 해주는 8배율 조준경",
    att_muzsup = "소음기",
    attSupDesc = "총기 소음을 줄여주는 소음기",
    att_exmag = "확장 탄알집",
    attEMagDesc = "총기의 탄약 장전양을 늘려주는 확장 탄알집",
    att_foregrip = "수직 손잡이",
    attForeDesc = "더 안정적이게 조준을 도와주는 수직 손잡이",
    att_laser = "레이저 조준기",
    attLaserDesc = "조준하는 곳을 가리켜주는 레이저 조준기",
    att_bipod = "양각대",
    attBipodDesc = "사격시 반동을 줄여주는 양각대",
    
    attDetached = "총기 부품을 떼냈습니다.",
    detTarget = "떼어낼 부품을 선택해 주세요.",
    cantAttached = "이 무기에는 해당 부품을 장착할 수 없습니다.",
    alreadyAttached = "무기에 빈자리가 없습니다.",
    notCW = "이 무기는 개조가능한 무기가 아닙니다.",
    notAttachment = "이건 올바른 총기 부품이 아닙니다.",
    noWeapon = "대상을 찾을수 없습니다.",

    cwReloading = "장전중 %s%%",
    cwMagKappa = "%s / %s",
    cwGrenades = "%sx 수류탄",
    cwEmptyM203 = "M203 장전필요",
    cwFilledM203 = "M203 장전 됨",
    cw40mm = "%sx 유탄",
    cwGrenType = "유탄종류: %s",
    cwUse = "[사용 키]", 
    cwStablize = "%s - 안정화",

    cwAmmo_ar2 = "소총 탄",
    cwAmmo_smg1 = "SMG 탄",
    cwAmmo_pistol = "권총 탄",
    cwAmmo_357 = "매그넘 탄",
	cwAmmo_sniperround = "저격소총 탄",
	cwAmmo_buckshot = "산탄 쉘",
}

