ITEM.name = "Soda Bottle"
ITEM.desc = "sodaBottleDesc"
ITEM.model = "models/props_junk/PopCan01a.mdl"
ITEM.hungerAmount = 15
ITEM.cookable = false
ITEM.foodDesc = "sodaCanDesc"
ITEM.price = 30
ITEM.quantity = 1
ITEM.staminaAmount = 30